# Generated by Django 2.2.8 on 2020-02-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='housedetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('area', models.CharField(max_length=30)),
                ('expected_rent', models.CharField(max_length=50)),
                ('expected_advance', models.CharField(max_length=50)),
                ('image', models.ImageField(default='', upload_to='houseowner/images')),
            ],
        ),
    ]
