# Generated by Django 2.2.8 on 2020-02-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseowner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ownerdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
