# Generated by Django 2.2.9 on 2020-02-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseowner', '0002_ownerdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housedetail',
            name='image',
            field=models.ImageField(upload_to='houseowner/images'),
        ),
    ]
