# Generated by Django 2.2.9 on 2020-02-23 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houseowner', '0003_auto_20200224_0218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ownerdetail',
        ),
    ]
