# Generated by Django 2.2.9 on 2020-02-23 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_ticketgenerate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketgenerate',
            old_name='username',
            new_name='uname',
        ),
    ]
