# Generated by Django 2.2.9 on 2020-02-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20200223_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketgenerate',
            name='reply',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ticketgenerate',
            name='status',
            field=models.CharField(default='Created', max_length=30),
        ),
    ]
