# Generated by Django 2.2.9 on 2020-02-23 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20200223_1720'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customerdetail',
        ),
    ]
